### ISSUE TITLE
Поменять описание в разделе "О клубе"

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/champion#10]
Плавание – красивый вид спорта, который очень благотворно воздействует на весь организм: работают все группы мышц, улучшает кровообмен, стимулирует сердечную деятельность, укрепляет дыхательную систему, формирует осанку, повышает иммунитет. Умение плавать заложено во всех людях на генетическом уровне, поэтому развить этот навык в себе может каждый. Миссия клуба состоит в том, чтобы помочь всем желающим обрести чувство свободы и уверенности в себе при нахождении в воде. 
_"Время течет – учитесь плавать!"_

**Comment by afrolovskiy** [comment]
Merged to master but not deployed.

**Comment by afrolovskiy** [comment]
Deployed
