### ISSUE TITLE
Добавить текст в раздел "Записаться"

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/champion#11]
Занятия проходят в группах по 8-12 человек, также есть возможность заниматься индивидуально. Группы формируются по возрасту и навыкам плавания. Мы стремимся сделать обучение не только эффективным, но и максимально комфортным.
**Для занятий Вам понадобятся:** 
1) Купальный костюм (плавки/ купальник);
2) Шапочка для плавания;
3) Очки для плавания;
4) Полотенце (для детей большое);
5) Резиновые тапочки;
6) Средства личной гигиены;
7) Пакет для уличной обуви;
8) Справка от врача.
**Документы:**
- Договор об оказании услуг
- Квитанция на оплату
- Согласие на обработку персональных данных

**Comment by afrolovskiy** [comment]
Merged to master but not deployed.

**Comment by afrolovskiy** [comment]
Deployed
