### ISSUE TITLE
Поменять иконку тренеры в разделе "Преимущества"

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/champion#12]
заменить значок человечка на значок с кепкой
![hat-clipart-coach-1](https://user-images.githubusercontent.com/33779023/53560053-a3a46200-3b5c-11e9-9272-a630e69bca11.png)

**Comment by afrolovskiy** [comment]
Merged to master but not deployed.

**Comment by afrolovskiy** [comment]
Deployed
