### ISSUE TITLE
В разделе документы поменять договор-оферту на новую версию и убрать квитанцию на оплату

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/champion#20]
[Дог-оферта (услуги плавания) v 2.pdf](https://github.com/afrolovskiy/champion/files/3176443/-.v.2.pdf)
[Как подготовить ребенка к бассейну.pdf](https://github.com/afrolovskiy/champion/files/3176452/default.pdf)

**Comment by afrolovskiy** [comment]
Сделал
