### ISSUE TITLE
добавить на сайт кнопки с оплатой и условия  по размещению информации от банка

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/champion#21]
сделал картинки как и что куда добавить в шапку, на сайт и в подвал
![способы оплаты](https://user-images.githubusercontent.com/33779023/57690919-7f303000-764b-11e9-9291-7d23e9e203bf.png)
![шкнопки в шапке](https://user-images.githubusercontent.com/33779023/57690920-7f303000-764b-11e9-9b8f-746bd7531da9.png)
![подвал с реквизитами](https://user-images.githubusercontent.com/33779023/57690921-7fc8c680-764b-11e9-8dee-f4eaf28c2730.png)

**Comment by AlexanderFrolovskiy** [comment]
А информацию в этом файле нужно разместить на отдельной странице сайта, чтобы можно было ссылки отправить в банк, а у нас на сайте можно просто ссылку сделать: правила оплаты
[правила оплаты картами  - ПЛАВАНИЕ.docx](https://github.com/afrolovskiy/champion/files/3216229/-.docx)

**Comment by AlexanderFrolovskiy** [comment]
Для соответствия присвоенной маркетинговой категории, разместите на вашем сайте следующую информацию: 
  - реквизиты компании (ИНН/ ОГРН)
  - цены на представленные товары
  - логотипы платежных систем "мир", "visa", "mastercard"
  - Политику безопасности: пример текста «При оплате заказа банковской картой, обработка платежа (включая ввод номера карты) происходит на защищенной странице процессинговой системы, которая прошла международную сертификацию. Это значит, что Ваши конфиденциальные данные (реквизиты карты, регистрационные данные и др.) не поступают в интернет-магазин, их обработка полностью защищена и никто, в том числе наш интернет-магазин, не может получить персональные и банковские данные клиента. При работе с карточными данными применяется стандарт защиты информации, разработанный международными платёжными системами Visa и MasterCard -Payment Card Industry Data Security Standard (PCI DSS), что обеспечивает безопасную обработку реквизитов Банковской карты Держателя. Применяемая технология передачи данных гарантирует безопасность по сделкам с Банковскими картами путем использования протоколов Secure Sockets Layer (SSL), Verifiedby Visa, Secure Code,и закрытых банковских сетей, имеющих высшую степень защиты.»
  - Политику возвратов: пример текста «Уважаемые Клиенты, информируем Вас о том, что при запросе возврата денежных средств при отказе от покупки, возврат производится исключительно на ту же банковскую карту, с которой была произведена оплата»

**Comment by AlexanderFrolovskiy** [comment]
Соответственно логотип Альфа-банка не нужен уже

**Comment by AlexanderFrolovskiy** [comment]
Реквизиты компании:
Полное наименование предприятия-организации
Общество с ограниченной ответственностью 
«ПРЕМЬЕР СЕРИЯ»
Сокращенное наименование предприятия-организации
ООО «ПРЕМЬЕР СЕРИЯ»
ИНН
7727769546
КПП
772701001
ОГРН
5117746062430 от 27.12.2011 г.
E-mail: info@swimchampion.ru
Телефон: 8(499)938-59-68

**Comment by AlexanderFrolovskiy** [comment]
это с левой стороны, а с правой давай разместим:
Проект представлен компанией 
ООО "Премьер серия"
и логотип
![logo](https://user-images.githubusercontent.com/33779023/60073004-e7ccfb00-9727-11e9-8cc0-b34ea4de0772.png)

**Comment by afrolovskiy** [comment]
Альфа-банк размещать не надо

Надо разместить платежные системы

Под ними:
Политика безопасности
Политика возвратов

Гиперссылки на страницы с текстом

>Гиперссылки на страницы с текстом

Какие страницы?) или что ты имеешь в виду? может всплывающие окна?

я просто хз(

или у киви есть эти страницы?

Давай всплываюшие окна

**Comment by AlexanderFrolovskiy** [comment]
![logo_mir](https://user-images.githubusercontent.com/33779023/60104276-cbea4900-9769-11e9-8009-1d5f19cf26e6.jpg)
![_Visa](https://user-images.githubusercontent.com/33779023/60104277-cc82df80-9769-11e9-9803-2135506f2e97.png)
![Mastercard-logo svg](https://user-images.githubusercontent.com/33779023/60104282-ce4ca300-9769-11e9-931a-599321a196f7.png)

**Comment by AlexanderFrolovskiy** [comment]
И стоимость снеси на отдельные строчки, пожалуйста:

**Стоимость:**
960 руб. / 1 раз в неделю
1920 руб. / 2 раза в неделю
