### ISSUE TITLE
закинуть документ на сайт в раздел записаться, по макету

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/champion#5]
[Дог-оферта (услуги плавания) v 2.pdf](https://github.com/afrolovskiy/champion/files/2899349/-.v.2.pdf)
[квитанция на оплату.pdf](https://github.com/afrolovskiy/champion/files/2899350/default.pdf)
а эти правила вставить в пункт ознакомиться, где галочка на обработку персональных данных
[Согласие на обработку персональных данных.pdf](https://github.com/afrolovskiy/champion/files/2899359/default.pdf)

**Comment by afrolovskiy** [comment]
Добавил.
