### ISSUE TITLE
добавить раздел Инструкторы на сайт

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/champion#8]
![default](https://user-images.githubusercontent.com/33779023/53480824-04fd0000-3a8d-11e9-81b7-21beb5b19184.png)
![default](https://user-images.githubusercontent.com/33779023/53480825-04fd0000-3a8d-11e9-908d-d3dbeee295f0.png)
![default](https://user-images.githubusercontent.com/33779023/53480826-04fd0000-3a8d-11e9-9884-332fafa2abc8.png)
![default](https://user-images.githubusercontent.com/33779023/53480828-05959680-3a8d-11e9-8d9e-a84d36604e8e.png)
![default](https://user-images.githubusercontent.com/33779023/53480829-05959680-3a8d-11e9-8eaf-88348d788ae2.png)
[Инструкторы.xlsx](https://github.com/afrolovskiy/champion/files/2909526/default.xlsx)

**Comment by afrolovskiy** [comment]
Пример раздела - https://user-images.githubusercontent.com/33779023/53509267-845df400-3acc-11e9-9bae-cbfef64f09f4.png

**Comment by afrolovskiy** [comment]
Разложил. @AlexanderFrolovskiy глянь плз описания. Вдруг я неправильно для кого из тренеров информацию указал.
