### ISSUE TITLE
добавить фотки на сайт в раздел "о клубе"

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/champion#9]
![default](https://user-images.githubusercontent.com/33779023/53509267-845df400-3acc-11e9-9bae-cbfef64f09f4.png)

![1](https://user-images.githubusercontent.com/33779023/53509319-a0fa2c00-3acc-11e9-90d3-877571647e02.png)
![1-1](https://user-images.githubusercontent.com/33779023/53509320-a0fa2c00-3acc-11e9-806f-84bfb255c3d8.png)
![2](https://user-images.githubusercontent.com/33779023/53509323-a0fa2c00-3acc-11e9-8fef-50e74d38080e.png)
![2-1](https://user-images.githubusercontent.com/33779023/53509326-a192c280-3acc-11e9-85a2-d0aa05ded586.png)
![3](https://user-images.githubusercontent.com/33779023/53509327-a192c280-3acc-11e9-998b-6d6f8b052728.png)
![3-1](https://user-images.githubusercontent.com/33779023/53509328-a192c280-3acc-11e9-886d-11ef45fa0821.png)
![4](https://user-images.githubusercontent.com/33779023/53509329-a192c280-3acc-11e9-8053-6e2bd9d6568f.png)
![4-1](https://user-images.githubusercontent.com/33779023/53509330-a22b5900-3acc-11e9-8212-c15ddfe91845.png)
![5](https://user-images.githubusercontent.com/33779023/53509331-a22b5900-3acc-11e9-8e21-afc9dd1c8736.png)
![5-1](https://user-images.githubusercontent.com/33779023/53509332-a22b5900-3acc-11e9-86d4-9c9dcc34569c.png)

**Comment by afrolovskiy** [comment]
Merged to master but not deployed.

**Comment by afrolovskiy** [comment]
Deployed
